NAME="office-dashboard"
HOST="johan@ssh.eprpi1.hostedpi.com"

# Config for barrel command
BARREL_DIR := lib
BARREL_FILE := barrel.dart
BARREL_PATH := $(BARREL_DIR)/$(BARREL_FILE)
FIND_CMD := find $(BARREL_DIR)/ -mindepth 1 -name '*.dart' -not -path "$(BARREL_PATH)"

info:
	echo "make reset           - flutter clean ; flutter pub get"
	echo "make build           - flutter build web --base-href /$(NAME)/"
	echo "make deploy          - build and deploy to $(HOST)"
	echo "make barrel          - update the $(BARREL_FILE) file in $(BARREL_PATH)"

.SILENT:

.PHONY: info reset update_pubspec update_phony build deploy barrel 

reset:
	flutter clean ; flutter pub get

build:
	figlet -f smslant "Clean build"
	flutter clean
	rm -fvr build
	figlet -f smslant "Build for web"
	flutter build web --base-href /$(NAME)/

deploy: build
	figlet -f smslant "Zip assets and upload"
	( cd build ; chmod -R a+r web ; mv web $(NAME) ; zip -r $(NAME).zip $(NAME) ; scp -P 5308 $(NAME).zip $(HOST): )
	figlet -f smslant "Server move"
	ssh -p 5308 $(HOST) ./deploy.sh $(NAME)

barrel:
	figlet -f smslant "Generating barrel"
	echo "Adding files to $(BARREL_PATH)..."
	@(	\
		echo "// Auto-generated by 'make barrel'. Do not edit directly."; \
		echo "// To update, run 'make barrel'."; \
		echo "// Exporting all files from: $(BARREL_DIR)"; \
		echo ""; \
		$(FIND_CMD) | sed "s#^$(BARREL_DIR)/##" | sort | sed "s#.*#export '&';#" || true \
	) > "$(BARREL_PATH)" 
	echo "✅ Barrel file '$(BARREL_PATH)' generated successfully."
