// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1PS4LnRvXu5USrSMczk-eTiupDAJTirU',
    appId: '1:716830583516:web:33a723354aef04fad4e219',
    messagingSenderId: '716830583516',
    projectId: 'pig-space',
    authDomain: 'pig-space.firebaseapp.com',
    storageBucket: 'pig-space.firebasestorage.app',
    measurementId: 'G-B22DK37XWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQHrC9NeQEi_M7ZdGNtz-LDLD1xodTTr4',
    appId: '1:716830583516:android:d8f8e6a3990fac30d4e219',
    messagingSenderId: '716830583516',
    projectId: 'pig-space',
    storageBucket: 'pig-space.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOSkVFZ2yY-aghkMCVzJ5JbiVs4rW3sTA',
    appId: '1:716830583516:ios:a31c87e6e9019f9fd4e219',
    messagingSenderId: '716830583516',
    projectId: 'pig-space',
    storageBucket: 'pig-space.firebasestorage.app',
    iosBundleId: 'com.example.flame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOSkVFZ2yY-aghkMCVzJ5JbiVs4rW3sTA',
    appId: '1:716830583516:ios:a31c87e6e9019f9fd4e219',
    messagingSenderId: '716830583516',
    projectId: 'pig-space',
    storageBucket: 'pig-space.firebasestorage.app',
    iosBundleId: 'com.example.flame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1PS4LnRvXu5USrSMczk-eTiupDAJTirU',
    appId: '1:716830583516:web:9be53eb8def24805d4e219',
    messagingSenderId: '716830583516',
    projectId: 'pig-space',
    authDomain: 'pig-space.firebaseapp.com',
    storageBucket: 'pig-space.firebasestorage.app',
    measurementId: 'G-06LL4DLVYB',
  );
}